syntax enable
set number
set cursorline
set mouse=a
set selection=exclusive
set selectmode=mouse,key
set tabstop=4
set autoindent
set visualbell
set noerrorbells
set nocompatible
set showmode
set showcmd
set t_Co=256
filetype indent on
set shiftwidth=4
set expandtab
set softtabstop=4
set relativenumber
set cursorline
set wrap
set linebreak
set wrapmargin=2
set scrolloff=5
set laststatus=2
set ruler
set showmatch
set hlsearch
set incsearch
set ignorecase
set smartcase
set autoread
set list
set wildmenu
set wildmode=longest:list,full
set listchars=tab:»·,trail:·
